! FT1 - 4-CPM turbo equalization mode for WSJT-X
! Copyright (C) 2026 Seth McCall, KD9TAW
!
! This file is part of WSJT-X.
!
! WSJT-X is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! WSJT-X is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with WSJT-X. If not, see <https://www.gnu.org/licenses/>.
!
subroutine ft1_interleave(bits_in,bits_out,ndir)

! S-random interleaver for FT1 turbo equalization
! Length 174 (LDPC codeword), S=9
!
! ndir = +1: forward (interleave)  -- LDPC bit order -> CPM symbol order
! ndir = -1: inverse (deinterleave) -- CPM symbol order -> LDPC bit order
!
! The permutation satisfies the S-random constraint:
!   |pi(i) - pi(j)| >= S for all |i - j| < S
! Optimized S-random interleaver: S=9, min_pair_sep=12, avg_pair_sep=74.3
! Generated by gen_interleaver_quick.py (seed=1000980, score=0.4499)

  integer, parameter :: N=174
  integer*1 bits_in(N), bits_out(N)
  integer ndir
  integer itable(N), itableinv(N)

! Forward permutation table (1-indexed): pi(k) maps LDPC position k -> CPM position pi(k)
  data itable/ &
    138,  25, 171,  78,  93,  63,  39, 159,   2, 114, 104,  53, 150,  18,  73, &
    133,  85, 172,  28, 112,   6, 144,  49,  94,  67, 124, 169,  16,  40, 154, &
     58,   3,  84, 141,  97, 125,  21, 164,  12, 108,  75,  43, 148,  61, 137, &
     30, 128, 162,  96, 119,  70, 174,  48, 140,  79,  32,  57, 100, 161,  13, &
    173, 113, 131,  74,  37, 122,   1,  87,  20,  59, 105,  47, 143,  11, 157, &
    118,  90, 129, 168, 107,  80, 142,  68,  22, 152,  56,  95, 116,  35, 130, &
     77, 106,  17, 167,   4, 149, 139,  34, 121,  51,  88, 102,  14, 160,  65, &
    146,  29, 123,  41, 111, 135, 170, 155,  52,  92,  19, 126,  31,  66, 117, &
     82, 153,  10, 163, 103,  46, 127,  64,  33,  86,  23,  55, 115,  76,  45, &
    136, 145,  99,   8, 158,  62, 110,  24,  42,  83, 134, 120,   9,  72,  60, &
    101,  26,  44, 151, 165,  81,  15,  71,  91, 109,   5,  50,  36, 166, 147, &
    132,  69,  27,  89, 156,  54,   7,  38,  98/

! Inverse permutation table (1-indexed): itableinv(k) maps CPM position k -> LDPC position
  data itableinv/ &
     67,   9,  32,  95, 161,  21, 172, 139, 148, 123,  74,  39,  60, 103, 157, &
     28,  93,  14, 116,  69,  37,  84, 131, 143,   2, 152, 168,  19, 107,  46, &
    118,  56, 129,  98,  89, 163,  65, 173,   7,  29, 109, 144,  42, 153, 135, &
    126,  72,  53,  23, 162, 100, 114,  12, 171, 132,  86,  57,  31,  70, 150, &
     44, 141,   6, 128, 105, 119,  25,  83, 167,  51, 158, 149,  15,  64,  41, &
    134,  91,   4,  55,  81, 156, 121, 145,  33,  17, 130,  68, 101, 169,  77, &
    159, 115,   5,  24,  87,  49,  35, 174, 138,  58, 151, 102, 125,  11,  71, &
     92,  80,  40, 160, 142, 110,  20,  62,  10, 133,  88, 120,  76,  50, 147, &
     99,  66, 108,  26,  36, 117, 127,  47,  78,  90,  63, 166,  16, 146, 111, &
    136,  45,   1,  97,  54,  34,  82,  73,  22, 137, 106, 165,  43,  96,  13, &
    154,  85, 122,  30, 113, 170,  75, 140,   8, 104,  59,  48, 124,  38, 155, &
    164,  94,  79,  27, 112,   3,  18,  61,  52/

  if(ndir.ge.0) then
! Forward interleave: bits_out(pi(k)) = bits_in(k)
     do k=1,N
        bits_out(itable(k)) = bits_in(k)
     enddo
  else
! Inverse interleave (deinterleave): bits_out(k) = bits_in(pi(k))
! Equivalently: bits_out(pi_inv(k)) = bits_in(k)
     do k=1,N
        bits_out(itableinv(k)) = bits_in(k)
     enddo
  endif

  return
end subroutine ft1_interleave
