! FT1 - 4-CPM turbo equalization mode for WSJT-X
! Copyright (C) 2026 Seth McCall, KD9TAW
!
! This file is part of WSJT-X.
!
! WSJT-X is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! WSJT-X is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with WSJT-X. If not, see <https://www.gnu.org/licenses/>.
!
module ldpc348_91_mod

! LDPC(348,91) rate-compatible mother code for FT1 IR-HARQ.
!
! Construction: Parity extension of LDPC(174,91).
!   - First 174 columns: identical to LDPC(174,91)
!   - Columns 175-261: RV1 extension parity (87 new bits)
!   - Columns 262-348: RV2 extension parity (87 new bits)
!
! H matrix structure (257 rows x 348 columns):
!   Rows   1- 83: original LDPC(174,91) H, zero-padded to 348 cols
!   Rows  84-170: extension rows connecting cols 175-261 to systematic bits
!   Rows 171-257: extension rows connecting cols 262-348 to systematic bits
!
! Nested rate-compatible codes:
!   LDPC(174,91): rate 0.523 (RV0 only)
!   LDPC(261,91): rate 0.349 (RV0 + RV1)
!   LDPC(348,91): rate 0.261 (RV0 + RV1 + RV2)
!
! Extension rows use PEG-optimized connections. Each new parity bit is
! connected to 5 columns from the base code (both systematic and parity
! bits), chosen by Progressive Edge Growth to maximize local girth (>=6)
! and balance column weights.
!
! Reference: specs/3d_protocol.md Section 8.2, ir_harq_protocol_design.md
! Generated by: research/phase2/gen_ldpc348_91.py

  implicit none

  integer, parameter :: N_MOTHER=348, K_MOTHER=91, M_MOTHER=257
  integer, parameter :: N_BASE=174, M_BASE=83
  integer, parameter :: N_EXT1=261, M_EXT1=170  !RV0+RV1
  integer, parameter :: N_EXT2=348, M_EXT2=257  !RV0+RV1+RV2
  integer, parameter :: N_NEW_PER_RV=87          !New parity bits per extension

  ! Maximum connections per row in extension (PEG: 6 connections each)
  integer, parameter :: MAX_ROW_WT_EXT=6

  ! Extension parity check connectivity (PEG-optimized, girth >= 6)
  ! ext1_cols(MAX_ROW_WT_EXT, N_NEW_PER_RV): columns connected to each ext1 row
  ! ext2_cols(MAX_ROW_WT_EXT, N_NEW_PER_RV): columns connected to each ext2 row
  ! Col 1: self-connection (new parity bit), Cols 2-6: PEG edges to base (1-174)
  integer :: ext1_cols(MAX_ROW_WT_EXT, N_NEW_PER_RV)
  integer :: ext1_nrw(N_NEW_PER_RV)              !Row weights for ext1
  integer :: ext2_cols(MAX_ROW_WT_EXT, N_NEW_PER_RV)
  integer :: ext2_nrw(N_NEW_PER_RV)              !Row weights for ext2

! PEG-optimized extension data -- generated by gen_ldpc348_91.py
! Extension 1 (RV1): 87 rows, self-connects 175-261, edges to cols 1-174
  data ext1_cols/ &
     175,  42, 160, 162, 100,  61, &
     176,  35, 105,  34,  62,  60, &
     177,  20,  12,  95, 109, 156, &
     178,  17,   1,  35, 135, 122, &
     179,  77, 130,  79,  84, 149, &
     180, 147,  58, 125,  81, 102, &
     181, 115,  67,  47, 119,  68, &
     182,  19, 128,  93,  18, 158, &
     183, 174,  14, 168, 117, 155, &
     184,  38, 112, 164,   3,  87, &
     185,  48, 171,  99, 136,  91, &
     186, 151,  43, 142,   2, 165, &
     187,  83,  51, 141,  39,  23, &
     188,  98,  49,   8, 118,  28, &
     189,  78, 108,  86,  88,  22, &
     190, 172,  29,  25,  92, 132, &
     191, 153, 139,  45,  56, 134, &
     192, 121, 126,  50, 170,  41, &
     193,  85, 124,  53, 161,  26, &
     194, 163,  96,  97,  65,  44, &
     195,  13, 120, 159,  10,  37, &
     196, 129,  73, 157,  69,  89, &
     197, 144, 101,  15,  36,  40, &
     198,  82,  94, 106,  81,  21, &
     199, 110, 154,  54, 123, 113, &
     200,  74,  24, 169,  64,  70, &
     201, 173,   5,  89, 166, 145, &
     202, 114,  80,  59,   7, 146, &
     203,  72,  55,  54,   4, 133, &
     204, 107, 148, 167, 103, 152, &
     205, 137,  46,  33,  90,  52, &
     206, 104,  53, 152, 150,  76, &
     207,  30, 131, 138,  57,  11, &
     208, 116, 118, 136, 113,  71, &
     209,   9, 143,  75, 111, 127, &
     210,  31,  66,  16,  90,  63, &
     211, 140,  27, 111,  32, 117, &
     212,   6,  58, 169,  38,  42, &
     213,  12,  11,  33,   9,  21, &
     214,  85,  79, 168, 142,  55, &
     215, 165,   7, 174, 120, 148, &
     216, 131, 118,   3,   1, 110, &
     217,  74,  34, 146,  44,  51, &
     218, 130, 170,  18, 164,  70, &
     219,  91, 131,  80,  86,  47, &
     220,  98, 161, 151, 100, 123, &
     221, 106,  84,  71,  99,  57, &
     222, 134,  14,   8,  61,  75, &
     223, 126, 150, 145, 159, 158, &
     224, 147, 173,  49,  16, 143, &
     225,  60, 120,  52, 127, 138, &
     226,  78,  18, 115,   6,  17, &
     227, 101,  51,  28, 107,  82, &
     228, 155, 114, 124, 135, 153, &
     229,  10, 102, 141, 166,  96, &
     230,  72, 160,  68, 171, 172, &
     231,  40,  65,  69,   2,  37, &
     232, 108, 149,  41,  59,  45, &
     233,   5,  24, 133,  19, 157, &
     234,  22,  62,  43, 163, 103, &
     235,  66,  78, 156,  64, 132, &
     236,  97,  48, 137,   4,  39, &
     237,  56, 129, 128,  95, 121, &
     238,  87, 113, 167,  63,  13, &
     239,  83,  76, 139, 112,  20, &
     240,  93, 144,  94, 125, 105, &
     241, 116, 121,  15, 140, 162, &
     242,  30,  67,  88, 122,  46, &
     243,  15,  23,  32,  25, 154, &
     244,  26,  32, 119,  29, 104, &
     245,  73,  46, 109,  92,  98, &
     246,  14,  37,  36,  60,  82, &
     247,  77, 134,  27,  43,  50, &
     248, 149,  31,  35,  56,  74, &
     249, 114, 122, 117, 103, 147, &
     250,  50, 153, 150,   2,  39, &
     251,  12, 143,  58, 166, 171, &
     252,  55,  38,  33, 135,  80, &
     253, 133,  20,   7, 102, 130, &
     254, 158,  13,  99,  30,  40, &
     255,  57,  16, 132,   3, 144, &
     256,  59,  67,   9, 163,  53, &
     257, 172, 126,  31,  44, 151, &
     258, 115,  89, 165, 125,  65, &
     259,   6,  54,  47, 162, 145, &
     260,  88,  63, 127, 152, 119, &
     261, 146, 156, 168,  17,  21/

  data ext1_nrw/87*6/

! Extension 2 (RV2): 87 rows, self-connects 262-348, edges to cols 1-174
  data ext2_cols/ &
     262,  41,  36, 162, 152, 119, &
     263,  90,  30,  43, 144,  64, &
     264,  28, 118,  77, 111,  86, &
     265,  62, 159, 104,  81,  60, &
     266, 105,  79, 125, 101, 133, &
     267,  94, 158, 114,  19, 150, &
     268, 142,  42, 160,  95,  39, &
     269, 134,  93,  44,  35, 155, &
     270, 147, 132, 114,  67,  74, &
     271,  63, 124,  84,  92, 130, &
     272,  71, 138, 149,  16,  33, &
     273, 131,  51, 166,  29,  65, &
     274,  10,  38,  31,  13,   8, &
     275,  26, 146,  70,   6, 117, &
     276, 116,  80, 113,  96,  24, &
     277, 172,  40,  88,  72,   2, &
     278,  68,  73,  98, 103, 148, &
     279,  76,  15, 120, 126, 168, &
     280,  45,  89,  61,  69,  32, &
     281,  37,  14, 122, 136,  55, &
     282,  52,  34, 121, 171, 143, &
     283,  12,   3, 173,   5,  47, &
     284,  75,  54, 115, 106, 128, &
     285,  58,  27, 139,  21,  48, &
     286,  97, 170, 127, 141, 110, &
     287, 145,  50,  85, 169, 123, &
     288,  53, 129,  56, 154, 102, &
     289,  17, 157,  25,  20,  59, &
     290,   4,  78, 161,   7,  22, &
     291,  66,  14, 140,  11, 153, &
     292, 137,  68,   9, 100,  23, &
     293,   1,  43, 150,  87,  46, &
     294, 135,  82, 165, 151,  99, &
     295,  83,  87, 163, 107, 174, &
     296,  49, 112,  24, 156, 164, &
     297, 109,  32, 108, 167,  30, &
     298,  18,  78, 155,  19,  91, &
     299,  57,  16, 121,  31, 124, &
     300, 144,  29, 116, 105, 110, &
     301,  97,  91,  49, 136, 132, &
     302, 139, 120, 103,  36,  25, &
     303,  84,  37,  59, 119, 113, &
     304, 109,  95,  61,  46, 149, &
     305, 168, 174, 165,  21,  28, &
     306,  66, 148,  51, 152,  39, &
     307,  74,  52,  12,  54,  70, &
     308, 133,  47, 166,  10, 170, &
     309,  96, 126, 140, 104, 142, &
     310,  69, 107, 141, 153,  93, &
     311,  72, 171,  86, 129,  38, &
     312,  48, 167,  83,   1,  22, &
     313, 157, 135, 161,  65,  60, &
     314,  57,   9, 173, 162,  26, &
     315,   8,  58,  41,  92,  79, &
     316,   4,  61,  81,   3,  15, &
     317,  63, 118, 151, 158,  33, &
     318,  42,  45,  98,   6,  90, &
     319, 112,  77, 145,  20, 143, &
     320, 154,  82, 117,   2,  89, &
     321,  50, 121, 160,  27, 159, &
     322, 172,  12, 138,  34, 130, &
     323,  40, 152,  75, 147, 156, &
     324, 164,  56,  94,  18, 163, &
     325,   5, 113, 169, 101,  88, &
     326,  85,  10,   7, 134,  80, &
     327,  73, 123, 146, 128, 137, &
     328, 122,  54,  53,  13,  17, &
     329, 125, 149,  62,  67, 106, &
     330, 102,  80,  47,  23, 108, &
     331,  55, 166, 127, 100,  35, &
     332,  11,  43, 138,  99, 115, &
     333,  76,  44, 131,  66,  55, &
     334,  71, 139,  64,  63,  38, &
     335, 111, 102,  52,  48,  31, &
     336,  83,  50,  67, 109,  42, &
     337, 105,  46, 126, 130, 106, &
     338, 174,  24,   1,  16,  29, &
     339,  96,  71,  97, 164,  30, &
     340,  60,  53,  70,  88,  75, &
     341, 135, 171, 160,  40, 137, &
     342, 167, 145,  11,  34,  17, &
     343,  69,   5, 100, 118, 147, &
     344,  73, 143,  13,  32, 129, &
     345, 103,  26, 170, 119,  90, &
     346,  86, 116,  49, 133,  87, &
     347, 159, 157, 125,  18,  39, &
     348, 141,  82, 156,  94,  78/

  data ext2_nrw/87*6/

contains

  subroutine init_ldpc348_91()
  ! No-op: extension data is now static DATA statements.
  ! Kept for API compatibility with existing callers.
  end subroutine init_ldpc348_91


  subroutine encode348_91(message91, codeword348)
  ! Encode a 91-bit message into a 348-bit mother codeword.
  !
  ! First 174 bits: standard LDPC(174,91) encoding
  ! Bits 175-261: RV1 extension parity (RA accumulate)
  ! Bits 262-348: RV2 extension parity (RA accumulate)

    implicit none
    integer*1, intent(in) :: message91(K_MOTHER)
    integer*1, intent(out) :: codeword348(N_MOTHER)
    integer*1 :: cw174(N_BASE)
    integer*1 :: msgbits77(77)
    integer :: i, j, nsum

    call init_ldpc348_91()   !No-op, kept for compatibility

    ! Standard LDPC(174,91) encoding for first 174 bits
    msgbits77 = message91(1:77)
    call encode174_91(msgbits77, cw174)
    codeword348(1:N_BASE) = cw174

    ! RV1 extension parity: each bit = XOR of connected systematic bits
    do i = 1, N_NEW_PER_RV
       nsum = 0
       do j = 2, ext1_nrw(i)          !Skip first col (self = new parity bit)
          nsum = nsum + codeword348(ext1_cols(j, i))
       enddo
       codeword348(N_BASE + i) = mod(nsum, 2)
    enddo

    ! RV2 extension parity: same structure
    do i = 1, N_NEW_PER_RV
       nsum = 0
       do j = 2, ext2_nrw(i)
          nsum = nsum + codeword348(ext2_cols(j, i))
       enddo
       codeword348(N_EXT1 + i) = mod(nsum, 2)
    enddo

  end subroutine encode348_91


  subroutine puncture_rv(codeword348, rv, transmitted174)
  ! Extract 174 bits to transmit for a given redundancy version.
  !
  ! RV0: bits 1-174 (standard LDPC(174,91) codeword)
  ! RV1: 87 new parity (175-261) + 87 highest-degree systematic (1-87)
  ! RV2: 87 new parity (262-348) + 87 mixed systematic/parity bits

    implicit none
    integer*1, intent(in) :: codeword348(N_MOTHER)
    integer, intent(in) :: rv
    integer*1, intent(out) :: transmitted174(N_BASE)

    select case(rv)
    case(0)
       ! RV0: standard first 174 bits
       transmitted174 = codeword348(1:N_BASE)

    case(1)
       ! RV1: 87 new parity bits + 87 systematic bits (for chase gain)
       transmitted174(1:87) = codeword348(N_BASE+1:N_EXT1)    !New parity
       transmitted174(88:174) = codeword348(1:87)              !Systematic repeat

    case(2)
       ! RV2: 87 new parity bits + 87 systematic bits
       transmitted174(1:87) = codeword348(N_EXT1+1:N_EXT2)    !New parity
       transmitted174(88:174) = codeword348(1:87)              !Systematic repeat

    case default
       transmitted174 = 0
    end select

  end subroutine puncture_rv


  subroutine bpdecode_ext(llr_combined, ncombined, maxiterations, &
       message77, nharderror, iter)
  ! BP decoder for extended LDPC codes: LDPC(261,91) or LDPC(348,91).
  !
  ! Uses the base LDPC(174,91) Tanner graph augmented with extension rows.
  ! Falls back to standard bpdecode174_91 on the first 174 LLRs if the
  ! extended decode fails (graceful degradation).
  !
  ! Input:
  !   llr_combined(ncombined) - combined LLRs (261 for RV0+1, 348 for RV0+1+2)
  !   ncombined               - 261 or 348
  !   maxiterations           - max BP iterations
  !
  ! Output:
  !   message77(77)           - decoded message bits
  !   nharderror              - number of hard errors (-1 if failed)
  !   iter                    - iterations used

    use iso_c_binding, only: c_loc, c_size_t
    use crc
    implicit none

    integer, intent(in) :: ncombined, maxiterations
    real, intent(in) :: llr_combined(ncombined)
    integer*1, intent(out) :: message77(77)
    integer, intent(out) :: nharderror, iter

    ! Local -- base code structures
    integer, parameter :: N=174, K=91, M=83
    ! Extended Tanner graph arrays
    integer, parameter :: MAX_CHECKS = M_MOTHER      !257
    integer, parameter :: MAX_BITS = N_MOTHER         !348

    integer :: nrw(M), ncw
    integer :: Nm(7,M), Mn(3,N)
    integer :: nrw_ext(MAX_CHECKS)
    integer :: Nm_ext(7, MAX_CHECKS)
    integer, parameter :: MAX_COL_WT = 9            !Max checks per bit (3 base + 3 ext1 + 3 ext2)
    integer :: Mn_ext(MAX_COL_WT, MAX_BITS)
    integer :: ncw_ext(MAX_BITS)                      !Checks per bit (variable)

    real :: zn(MAX_BITS), tov(MAX_COL_WT,MAX_BITS), toc(7,MAX_CHECKS)
    real :: tanhtoc(7,MAX_CHECKS)
    integer*1 :: cw(MAX_BITS), decoded(K)
    integer :: synd(MAX_CHECKS)
    integer :: nrows, ncols
    integer :: i, j, kk, ibj, ichk, ncheck, ncnt, nclast, nd, nbadcrc, nsum
    real :: Tmn, y

    ! Base code parity check data (DATA statements for Mn, Nm, nrw, ncw)
    include "../ft8/ldpc_174_91_c_parity.f90"

    call init_ldpc348_91()   !No-op, kept for compatibility

    nharderror = -1
    message77 = 0

    ! Determine extended code dimensions
    if(ncombined .eq. N_EXT1) then
       nrows = M_EXT1                   !170
       ncols = N_EXT1                   !261
    else if(ncombined .eq. N_EXT2) then
       nrows = M_EXT2                   !257
       ncols = N_EXT2                   !348
    else
       ! Unknown size -- fall back to base decode
       call fallback_base_decode()
       return
    endif

    ! Build extended Tanner graph
    ! Start with base graph
    Nm_ext = 0
    Mn_ext = 0
    ncw_ext = 0
    nrw_ext = 0

    ! Copy base parity check matrix (rows 1-83)
    do j = 1, M
       nrw_ext(j) = nrw(j)
       Nm_ext(1:7, j) = Nm(1:7, j)
    enddo
    do i = 1, N
       ncw_ext(i) = ncw          !3 for base code
       Mn_ext(1:3, i) = Mn(1:3, i)
    enddo

    ! Add extension 1 rows (84-170) for bits 175-261
    if(ncols .ge. N_EXT1) then
       do i = 1, N_NEW_PER_RV
          j = M + i                    !Row index in extended graph
          nrw_ext(j) = ext1_nrw(i)
          do kk = 1, ext1_nrw(i)
             Nm_ext(kk, j) = ext1_cols(kk, i)
             ! Also update column-to-row mapping
             ibj = ext1_cols(kk, i)
             ncw_ext(ibj) = ncw_ext(ibj) + 1
             if(ncw_ext(ibj) .le. MAX_COL_WT) then
                Mn_ext(ncw_ext(ibj), ibj) = j
             endif
          enddo
       enddo
    endif

    ! Add extension 2 rows (171-257) for bits 262-348
    if(ncols .ge. N_EXT2) then
       do i = 1, N_NEW_PER_RV
          j = M_EXT1 + i              !Row index
          nrw_ext(j) = ext2_nrw(i)
          do kk = 1, ext2_nrw(i)
             Nm_ext(kk, j) = ext2_cols(kk, i)
             ibj = ext2_cols(kk, i)
             ncw_ext(ibj) = ncw_ext(ibj) + 1
             if(ncw_ext(ibj) .le. MAX_COL_WT) then
                Mn_ext(ncw_ext(ibj), ibj) = j
             endif
          enddo
       enddo
    endif

    ! BP decoding on extended graph
    toc = 0.0
    tov = 0.0
    tanhtoc = 0.0

    ! Initialize check-to-variable messages
    do j = 1, nrows
       do i = 1, nrw_ext(j)
          ibj = Nm_ext(i, j)
          if(ibj .ge. 1 .and. ibj .le. ncols) then
             toc(i, j) = llr_combined(ibj)
          endif
       enddo
    enddo

    ncnt = 0
    nclast = 0

    do iter = 0, maxiterations

       ! Update bit LLRs
       do i = 1, ncols
          zn(i) = llr_combined(i) + sum(tov(1:ncw_ext(i), i))
       enddo

       ! Syndrome check
       cw(1:ncols) = 0
       where(zn(1:ncols) .gt. 0.0) cw(1:ncols) = 1
       ncheck = 0
       do i = 1, nrows
          nsum = 0
          do kk = 1, nrw_ext(i)
             ibj = Nm_ext(kk, i)
             if(ibj .ge. 1 .and. ibj .le. ncols) nsum = nsum + cw(ibj)
          enddo
          synd(i) = mod(nsum, 2)
          if(synd(i) .ne. 0) ncheck = ncheck + 1
       enddo

       if(ncheck .eq. 0) then
          decoded = cw(1:K)
          call chkcrc14a(decoded, nbadcrc)
          nharderror = count((2*cw(1:ncols)-1) * llr_combined(1:ncols) .lt. 0.0)
          if(nbadcrc .eq. 0) then
             message77 = decoded(1:77)
             return
          endif
       endif

       ! Early stopping
       if(iter .gt. 0) then
          nd = ncheck - nclast
          if(nd .lt. 0) then
             ncnt = 0
          else
             ncnt = ncnt + 1
          endif
          if(ncnt .ge. 5 .and. iter .ge. 10 .and. ncheck .gt. 15) then
             nharderror = -1
             return
          endif
       endif
       nclast = ncheck

       ! Bit-to-check messages
       do j = 1, nrows
          do i = 1, nrw_ext(j)
             ibj = Nm_ext(i, j)
             if(ibj .lt. 1 .or. ibj .gt. ncols) cycle
             toc(i, j) = zn(ibj)
             do kk = 1, ncw_ext(ibj)
                if(Mn_ext(kk, ibj) .eq. j) then
                   toc(i, j) = toc(i, j) - tov(kk, ibj)
                endif
             enddo
          enddo
       enddo

       ! Check-to-bit messages
       do i = 1, nrows
          do kk = 1, nrw_ext(i)
             tanhtoc(kk, i) = tanh(-toc(kk, i) / 2.0)
          enddo
       enddo

       do j = 1, ncols
          do i = 1, ncw_ext(j)
             ichk = Mn_ext(i, j)
             if(ichk .lt. 1 .or. ichk .gt. nrows) cycle
             Tmn = product(tanhtoc(1:nrw_ext(ichk), ichk), &
                  mask=Nm_ext(1:nrw_ext(ichk), ichk) .ne. j)
             call platanh(-Tmn, y)
             tov(i, j) = 2.0 * y
          enddo
       enddo

    enddo  !iter

    ! BP failed -- try fallback on base code LLRs
    call fallback_base_decode()
    return

  contains

    subroutine fallback_base_decode()
      ! Fall back to standard LDPC(174,91) BP decode using first 174 LLRs
      integer*1 :: apmask_zero(N_BASE)
      integer*1 :: cw_base(N_BASE)
      integer :: ncheck_base

      apmask_zero = 0
      call bpdecode174_91(llr_combined(1:N_BASE), apmask_zero, maxiterations, &
           message77, cw_base, nharderror, iter, ncheck_base)
    end subroutine fallback_base_decode

  end subroutine bpdecode_ext


  subroutine bpdecode_ext_soft(llr_combined, ncombined, maxiterations, &
       message77, zn_out, nharderror, ncheck_out, iter)
  ! Soft-output sibling of bpdecode_ext: identical BP on the extended Tanner
  ! graph, but also returns the per-bit a-posteriori belief zn_out(1:ncombined)
  ! and the final unsatisfied-check count ncheck_out, so a joint-turbo HARQ
  ! caller can form the LDPC extrinsic (zn_out - channel_llr) to feed back into
  ! the per-frame BCJR. Supports ncombined = N_EXT1 (261) or N_EXT2 (348).
    use crc
    implicit none
    integer, intent(in)  :: ncombined, maxiterations
    real,    intent(in)  :: llr_combined(ncombined)
    integer*1, intent(out) :: message77(77)
    real,    intent(out) :: zn_out(ncombined)
    integer, intent(out) :: nharderror, ncheck_out, iter

    integer, parameter :: N=174, K=91, M=83
    integer, parameter :: MAX_CHECKS = M_MOTHER
    integer, parameter :: MAX_BITS   = N_MOTHER
    integer, parameter :: MAX_COL_WT = 9
    integer :: nrw(M), ncw
    integer :: Nm(7,M), Mn(3,N)
    integer :: nrw_ext(MAX_CHECKS), Nm_ext(7,MAX_CHECKS)
    integer :: Mn_ext(MAX_COL_WT,MAX_BITS), ncw_ext(MAX_BITS)
    real    :: zn(MAX_BITS), tov(MAX_COL_WT,MAX_BITS), toc(7,MAX_CHECKS)
    real    :: tanhtoc(7,MAX_CHECKS)
    integer*1 :: cw(MAX_BITS), decoded(K)
    integer :: synd(MAX_CHECKS)
    integer :: nrows, ncols
    integer :: i, j, kk, ibj, ichk, ncheck, ncnt, nclast, nd, nbadcrc, nsum
    real    :: Tmn, y

    include "../ft8/ldpc_174_91_c_parity.f90"

    call init_ldpc348_91()
    nharderror = -1; message77 = 0; ncheck_out = 99; zn_out = 0.0

    if(ncombined .eq. N_EXT1) then
       nrows = M_EXT1; ncols = N_EXT1
    else if(ncombined .eq. N_EXT2) then
       nrows = M_EXT2; ncols = N_EXT2
    else
       return                     !only extended sizes supported
    endif

    ! Build extended Tanner graph (identical to bpdecode_ext)
    Nm_ext = 0; Mn_ext = 0; ncw_ext = 0; nrw_ext = 0
    do j = 1, M
       nrw_ext(j) = nrw(j); Nm_ext(1:7,j) = Nm(1:7,j)
    enddo
    do i = 1, N
       ncw_ext(i) = ncw; Mn_ext(1:3,i) = Mn(1:3,i)
    enddo
    if(ncols .ge. N_EXT1) then
       do i = 1, N_NEW_PER_RV
          j = M + i; nrw_ext(j) = ext1_nrw(i)
          do kk = 1, ext1_nrw(i)
             Nm_ext(kk,j) = ext1_cols(kk,i); ibj = ext1_cols(kk,i)
             ncw_ext(ibj) = ncw_ext(ibj) + 1
             if(ncw_ext(ibj) .le. MAX_COL_WT) Mn_ext(ncw_ext(ibj),ibj) = j
          enddo
       enddo
    endif
    if(ncols .ge. N_EXT2) then
       do i = 1, N_NEW_PER_RV
          j = M_EXT1 + i; nrw_ext(j) = ext2_nrw(i)
          do kk = 1, ext2_nrw(i)
             Nm_ext(kk,j) = ext2_cols(kk,i); ibj = ext2_cols(kk,i)
             ncw_ext(ibj) = ncw_ext(ibj) + 1
             if(ncw_ext(ibj) .le. MAX_COL_WT) Mn_ext(ncw_ext(ibj),ibj) = j
          enddo
       enddo
    endif

    toc = 0.0; tov = 0.0; tanhtoc = 0.0
    do j = 1, nrows
       do i = 1, nrw_ext(j)
          ibj = Nm_ext(i,j)
          if(ibj .ge. 1 .and. ibj .le. ncols) toc(i,j) = llr_combined(ibj)
       enddo
    enddo
    ncnt = 0; nclast = 0

    do iter = 0, maxiterations
       do i = 1, ncols
          zn(i) = llr_combined(i) + sum(tov(1:ncw_ext(i),i))
       enddo
       cw(1:ncols) = 0
       where(zn(1:ncols) .gt. 0.0) cw(1:ncols) = 1
       ncheck = 0
       do i = 1, nrows
          nsum = 0
          do kk = 1, nrw_ext(i)
             ibj = Nm_ext(kk,i)
             if(ibj .ge. 1 .and. ibj .le. ncols) nsum = nsum + cw(ibj)
          enddo
          synd(i) = mod(nsum,2)
          if(synd(i) .ne. 0) ncheck = ncheck + 1
       enddo
       ncheck_out = ncheck
       zn_out(1:ncols) = zn(1:ncols)
       if(ncheck .eq. 0) then
          decoded = cw(1:K)
          call chkcrc14a(decoded, nbadcrc)
          nharderror = count((2*cw(1:ncols)-1)*llr_combined(1:ncols) .lt. 0.0)
          if(nbadcrc .eq. 0) then
             message77 = decoded(1:77)
             return
          endif
       endif
       if(iter .gt. 0) then
          nd = ncheck - nclast
          if(nd .lt. 0) then; ncnt = 0; else; ncnt = ncnt + 1; endif
          if(ncnt .ge. 5 .and. iter .ge. 10 .and. ncheck .gt. 15) then
             nharderror = -1
             return
          endif
       endif
       nclast = ncheck
       do j = 1, nrows
          do i = 1, nrw_ext(j)
             ibj = Nm_ext(i,j)
             if(ibj .lt. 1 .or. ibj .gt. ncols) cycle
             toc(i,j) = zn(ibj)
             do kk = 1, ncw_ext(ibj)
                if(Mn_ext(kk,ibj) .eq. j) toc(i,j) = toc(i,j) - tov(kk,ibj)
             enddo
          enddo
       enddo
       do i = 1, nrows
          do kk = 1, nrw_ext(i)
             tanhtoc(kk,i) = tanh(-toc(kk,i)/2.0)
          enddo
       enddo
       do j = 1, ncols
          do i = 1, ncw_ext(j)
             ichk = Mn_ext(i,j)
             if(ichk .lt. 1 .or. ichk .gt. nrows) cycle
             Tmn = product(tanhtoc(1:nrw_ext(ichk),ichk), &
                  mask=Nm_ext(1:nrw_ext(ichk),ichk) .ne. j)
             call platanh(-Tmn, y)
             tov(i,j) = 2.0*y
          enddo
       enddo
    enddo
    nharderror = -1
    return
  end subroutine bpdecode_ext_soft

end module ldpc348_91_mod
